development:
  domain: 'trosic.com'
  username: 'mailers@trosic.com'
  password: '58Y36s71f6iQ17KX2Zj43Y7+J0'

test:
  domain: 'trosic.com'
  username: 'mailers@trosic.com'
  password: '58Y36s71f6iQ17KX2Zj43Y7+J0'

production:
  domain: 'trosic.com'
  username: 'mailers@trosic.com'
  password: '58Y36s71f6iQ17KX2Zj43Y7+J0'